game_scm_pre_unwind_handler(): Fix potential format string crash
Use g_set_error_literal() for setting the error message to the stack trace, as
this might contain format string macros. Spotted by building with
-Werror=format-security:

game.c: In function 'game_scm_pre_unwind_handler':
game.c:425:24: error: format not a string literal and no format arguments [-Werror=format-security]
(cherry picked from commit 3e6a3c973992905a25a24102423322f8a4a01977)